const { Schema, model } = require("mongoose");

const SavedGitHubRepoSchema = new Schema({
  //the following values are read via the github api
  owner: {
    type: String,
    required: true,
  },
  repositoryName: {
    type: String,
    required: true,
  },
  gitHubID: {
    type: Number,
    required: true,
  },
  comments: [{ type: Schema.Types.ObjectId, ref: "Comments" }],
  _id: { type: Schema.Types.ObjectId, default: () => new Types.ObjectId() }, //default id generated by mongo
});

const SavedGitHubRepo = model("SavedGitHubRepo", SavedGitHubRepoSchema);

module.exports = SavedGitHubRepo;
